import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: {
    locale: string
  }
}

const layout = ({
    children,
    params: {
        locale
    }
}: Readonly<LayoutProps>) => {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        {/* Layout UI */}
        <div className="h-screen bg-[aliceblue]">
          {children}
        </div>
      </body>
    </html>
  );
}

export default layout;